#!/usr/bin/env python3
"""SecondBrainKit V2 lifecycle CLI.

Mutating commands are snapshot-first and idempotent. The CLI itself uses only
the Python standard library; retrieval dependencies are isolated in the Kit
venv and checked by `doctor`.
"""
from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import importlib.util
import json
import os
import platform
import re
import shutil
import subprocess
import sys
import tarfile
import tempfile
import tomllib
import urllib.request
from pathlib import Path


KIT = Path(__file__).resolve().parent
VERSION = (KIT / "VERSION").read_text(encoding="utf-8").strip()
CONFIG_SCHEMA = 2
DATA_SCHEMA = 2
DEFAULT_ROOT = Path.home() / "SecondBrain"
TIERS_FILE = KIT / "TIERS.toml"


# ══════════════════════════════════════════════════════════════════════
# ТИРИ
#
# Тири нашаровуються: v2 = v1 + своє, v3 = v2 + своє. Жоден тир не
# перевизначає файли нижчого, тому «встановити одразу v3» і «пройти
# v1 → v2 → v3» дають ІДЕНТИЧНИЙ результат — це властивість, яку
# перевіряє tests/test_tiers.py, а не побажання.
# ══════════════════════════════════════════════════════════════════════

def load_tiers() -> dict:
    if not TIERS_FILE.exists():
        raise SystemExit(f"ERROR: нема маніфесту тирів: {TIERS_FILE}")
    with TIERS_FILE.open("rb") as handle:
        return tomllib.load(handle)


def tier_table(manifest: dict | None = None) -> dict[str, dict]:
    return (manifest or load_tiers()).get("tier", {})


def tier_order(tier_id: str, manifest: dict | None = None) -> int:
    table = tier_table(manifest)
    if tier_id not in table:
        known = ", ".join(sorted(table, key=lambda t: table[t]["order"]))
        raise SystemExit(f"ERROR: невідомий тир {tier_id!r}. Відомі: {known}")
    return int(table[tier_id]["order"])


def tiers_upto(tier_id: str, manifest: dict | None = None) -> list[str]:
    """Кумулятивний список тирів від найнижчого до заданого."""
    manifest = manifest or load_tiers()
    table = tier_table(manifest)
    target = tier_order(tier_id, manifest)
    return sorted((t for t, v in table.items() if int(v["order"]) <= target),
                  key=lambda t: int(table[t]["order"]))


def tier_files(tier_id: str, manifest: dict | None = None) -> list[Path]:
    """Файли ОДНОГО тиру (без нижчих), що реально є в цьому чекауті."""
    manifest = manifest or load_tiers()
    found: set[Path] = set()
    for pattern in tier_table(manifest)[tier_id].get("paths", []):
        for path in KIT.glob(pattern):
            if path.is_file():
                found.add(path.relative_to(KIT))
    return sorted(found)


def resolve_files(tier_id: str, manifest: dict | None = None) -> list[Path]:
    """Кумулятивний набір файлів для тиру — те, що людина фактично отримує."""
    manifest = manifest or load_tiers()
    out: set[Path] = set()
    for tier in tiers_upto(tier_id, manifest):
        out.update(tier_files(tier, manifest))
    return sorted(out)


def tier_available(tier_id: str, manifest: dict | None = None) -> bool:
    """Чи фізично є цей шар у цій збірці (а не лише згадка про нього)."""
    manifest = manifest or load_tiers()
    meta = tier_table(manifest).get(tier_id, {})
    if meta.get("available") is False:
        return False
    return bool(meta.get("paths"))


def available_tiers(manifest: dict | None = None) -> list[str]:
    manifest = manifest or load_tiers()
    table = tier_table(manifest)
    return [t for t in sorted(table, key=lambda x: int(table[x]["order"]))
            if tier_available(t, manifest)]


def tier_of_file(rel: Path, manifest: dict | None = None) -> str | None:
    manifest = manifest or load_tiers()
    for tier in tier_table(manifest):
        if rel in set(tier_files(tier, manifest)):
            return tier
    return None


def now_slug() -> str:
    return dt.datetime.now().astimezone().strftime("%Y%m%d-%H%M%S")


def as_path(value: str | Path) -> Path:
    return Path(value).expanduser().resolve()


def json_write(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    tmp.replace(path)


def toml_string(value: str | Path) -> str:
    return json.dumps(str(value), ensure_ascii=False)


def render_config(root: Path, profile: str, tier: str = "v2") -> str:
    archives = root / "archives"
    return f"""# Generated by SecondBrainKit {VERSION}
[kit]
version = {toml_string(VERSION)}
config_schema = {CONFIG_SCHEMA}
data_schema = {DATA_SCHEMA}
profile = {toml_string(profile)}
tier = {toml_string(tier)}

[user]
name = "Користувач"

[vault]
root = {toml_string(root)}
memory = {toml_string(root / "memory")}
inbox = {toml_string(root / "inbox")}
tasks = {toml_string(root / "tasks")}
external = {toml_string(root / "external")}

[archives]
chatgpt = {toml_string(archives / "chatgpt")}
gemini = {toml_string(archives / "gemini")}
claude = {toml_string(archives / "claude")}
knowledge = {toml_string(root / "knowledge")}
claude_code = {toml_string(archives / "claude-code")}
codex = {toml_string(archives / "codex")}

[live_sources]
claude_code_sessions = {toml_string(Path.home() / ".claude" / "projects")}
codex_sessions = {toml_string(Path.home() / ".codex" / "sessions")}

[maintenance]
log_path = {toml_string(root / "log.md")}
backup_dir = {toml_string(root / ".backups")}
diagnostic_dir = {toml_string(Path.home() / ".config" / "second-brain" / "logs")}

[claude_code]
projects_dir = {toml_string(Path.home() / ".claude" / "projects")}
skills_dir = {toml_string(Path.home() / ".claude" / "skills")}

[index]
db_path = {toml_string(root / ".index" / "index.db")}

[embed]
ollama_url = "http://localhost:11434"
ollama_model = "bge-m3"
openrouter_enabled = false
openrouter_model = "baai/bge-m3"
env_file = {toml_string(Path.home() / ".config" / "second-brain" / ".env")}
"""


def state_path(root: Path) -> Path:
    return root / ".sbkit" / "state.json"


def load_state(root: Path) -> dict:
    path = state_path(root)
    if not path.exists():
        return {}
    return json.loads(path.read_text(encoding="utf-8"))


def record_state(root: Path, *, profile: str, agents: list[str],
                 config: Path, backup: Path | None = None,
                 tier: str | None = None) -> dict:
    previous = load_state(root)
    tier = tier or previous.get("tier", "v2")
    operations = previous.get("operations", [])
    operations.append({"at": dt.datetime.now().astimezone().isoformat(),
                       "version": VERSION, "tier": tier})
    history = previous.get("tier_history", [])
    if not history or history[-1]["tier"] != tier:
        history.append({"tier": tier, "at": dt.datetime.now().astimezone().isoformat()})
    payload = {
        "kit_version": VERSION,
        "config_schema": CONFIG_SCHEMA,
        "data_schema": DATA_SCHEMA,
        "root": str(root),
        "config": str(config),
        "profile": profile,
        "tier": tier,
        "tier_history": history[-20:],
        "agents": sorted(set(agents)),
        "last_backup": str(backup) if backup else previous.get("last_backup"),
        "operations": operations[-50:],
    }
    json_write(state_path(root), payload)
    return payload


def checksum(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def create_backup(root: Path, destination: Path | None = None) -> Path:
    if not root.exists():
        raise SystemExit(f"ERROR: root does not exist: {root}")
    backup_dir = destination or root / ".backups"
    backup_dir.mkdir(parents=True, exist_ok=True)
    archive = backup_dir / f"sbkit-{now_slug()}.tar.gz"
    manifest: dict[str, str] = {}
    with tarfile.open(archive, "w:gz") as tar:
        for path in sorted(root.rglob("*")):
            if not path.is_file():
                continue
            rel = path.relative_to(root)
            if rel.parts and rel.parts[0] in {".backups", ".index"}:
                continue
            manifest[str(rel)] = checksum(path)
            tar.add(path, arcname=Path("data") / rel, recursive=False)
        data = json.dumps(
            {"created": dt.datetime.now().astimezone().isoformat(),
             "root": str(root), "files": manifest},
            ensure_ascii=False, indent=2,
        ).encode("utf-8")
        info = tarfile.TarInfo("MANIFEST.json")
        info.size = len(data)
        tar.addfile(info, fileobj=__import__("io").BytesIO(data))
    return archive


def safe_members(tar: tarfile.TarFile) -> list[tarfile.TarInfo]:
    members = []
    for member in tar.getmembers():
        path = Path(member.name)
        if path.is_absolute() or ".." in path.parts:
            raise SystemExit(f"ERROR: unsafe archive member: {member.name}")
        members.append(member)
    return members


def restore_backup(root: Path, archive: Path, *, snapshot: bool = True) -> Path | None:
    if not archive.exists():
        raise SystemExit(f"ERROR: backup does not exist: {archive}")
    before = create_backup(root) if snapshot and root.exists() else None
    root.mkdir(parents=True, exist_ok=True)
    with tarfile.open(archive, "r:gz") as tar:
        members = safe_members(tar)
        for member in members:
            if not member.name.startswith("data/") or not member.isfile():
                continue
            rel = Path(member.name).relative_to("data")
            target = root / rel
            target.parent.mkdir(parents=True, exist_ok=True)
            source = tar.extractfile(member)
            if source is None:
                continue
            tmp = target.with_suffix(target.suffix + ".restore")
            with tmp.open("wb") as handle:
                shutil.copyfileobj(source, handle)
            tmp.replace(target)
    return before


def adapter_text(name: str, root: Path, config: Path, tier: str = "v2") -> str:
    """Інструкція для агента. Зростає разом із тиром — це і є різниця, яку
    агент фактично бачить: v3 додає йому обов'язок звіряти сказане із записаним."""
    base = KIT / "templates" / name
    if not base.exists():
        # 🔴 23.08.2026: у нижчому тирі шаблону може не бути. Раніше тут летів
        # FileNotFoundError посеред установки — людина отримувала стектрейс і
        # напів-поставлену базу. Відсутній шаблон означає «цього агента цей тир
        # не веде», а не «установка зламалась».
        raise FileNotFoundError(
            f"шаблон {name} не входить у тир {tier} — цього агента цей тир не веде"
        )
    parts = [base.read_text(encoding="utf-8")]
    for level in tiers_upto(tier):
        fragment = KIT / "templates" / f"tier-{level}.fragment.md"
        if fragment.exists():
            parts.append(fragment.read_text(encoding="utf-8"))
    text = "\n".join(part.rstrip() + "\n" for part in parts)
    return (text.replace("<KIT>", str(KIT)).replace("<ROOT>", str(root))
                .replace("<CONFIG>", str(config)).replace("<TIER>", tier))


def write_if_changed(path: Path, text: str) -> bool:
    if path.exists() and path.read_text(encoding="utf-8") == text:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(text, encoding="utf-8")
    tmp.replace(path)
    return True


def deps_present() -> dict:
    """Чи стоять залежності — у ТОМУ інтерпретаторі, яким кит реально працює.

    🔴 23.08.2026. Раніше тут стояв find_spec() у поточному процесі. Але install.sh
    запускає sbkit.py системним python3, а залежності ставить у .venv кита — тож
    бездоганно поставлена база рапортувала ready=false і радила «run: bash
    scripts/setup.sh», який людина щойно виконала. Новачок читає це як «зламалось»
    і йде питати автора. Міряти треба той python, який працюватиме, а не той,
    яким ми випадково запустились.
    """
    venv = KIT / ".venv" / "bin" / "python"
    if venv.exists():
        probe = ("import importlib.util as u,json;"
                 "print(json.dumps({m: u.find_spec(m) is not None "
                 "for m in ('sqlite_vec','numpy')}))")
        try:
            out = subprocess.run([str(venv), "-c", probe], capture_output=True,
                                 text=True, timeout=30)
            if out.returncode == 0:
                return json.loads(out.stdout.strip())
        except Exception:
            pass  # не змогли спитати .venv — падаємо до поточного процесу
    return {m: importlib.util.find_spec(m) is not None
            for m in ("sqlite_vec", "numpy")}


def cmd_doctor(args: argparse.Namespace) -> int:
    config = as_path(args.config) if args.config else None
    report = {
        "kit_version": VERSION,
        "platform": platform.platform(),
        "supported": sys.platform == "darwin" or sys.platform.startswith("linux"),
        "python": platform.python_version(),
        "python_ok": sys.version_info >= (3, 11),
        "git": shutil.which("git"),
        "ollama": False,
        **deps_present(),
        "config": str(config) if config else None,
        "config_ok": False,
        "issues": [],
    }
    try:
        urllib.request.urlopen("http://localhost:11434/api/tags", timeout=1)
        report["ollama"] = True
    except Exception:
        pass
    if not report["python_ok"]:
        report["issues"].append("Python 3.11+ required")
    if not report["supported"]:
        report["issues"].append("Windows/WSL is not supported in 2.0")
    if config:
        try:
            with config.open("rb") as handle:
                cfg = tomllib.load(handle)
            schema = int(cfg.get("kit", {}).get("config_schema", 1))
            report["config_ok"] = schema <= CONFIG_SCHEMA
            report["config_schema"] = schema
        except Exception as exc:
            report["issues"].append(f"invalid config: {exc}")
    if not report["sqlite_vec"] or not report["numpy"]:
        report["issues"].append(
            "залежності не стоять у .venv кита — полагодити: bash scripts/setup.sh")
    ready = (
        report["python_ok"] and report["supported"]
        and report["sqlite_vec"] and report["numpy"]
        and (not config or report["config_ok"])
    )
    report["ready"] = ready
    state: dict = {}
    try:
        manifest = load_tiers()
        state = load_state(as_path(args.root)) if getattr(args, "root", None) else {}
        report["tier"] = state.get("tier") or manifest.get("default")
        report["layers"] = tiers_upto(report["tier"], manifest)
        report["files_active"] = len(resolve_files(report["tier"], manifest))
    except SystemExit:
        report["tier"] = None
    hooks = hooks_wired(state.get("agents"))
    report["hooks"] = hooks
    for agent, wired in hooks.items():
        if wired is False:
            report["issues"].append(
                f"хуки для {agent} не підключені — компакт-щит і авто-пригадування "
                f"НЕ працюють, хоч файли стоять (див. docs/05-hooks.md, docs/18-codex-hooks.md)")
            ready = False
    report["ready"] = ready
    hint = companion_hint()
    if hint:
        report["companion"] = hint
    print(json.dumps(report, ensure_ascii=False, indent=2))
    return 0 if ready else 1


# 🔴 22.08.2026 — дірка, знайдена на живій установці: кит стояв, doctor казав
# «усе працює», а хуки в Codex не були підключені взагалі. Тобто головна фіча
# (щит контексту) мовчки не існувала, і користувач знайшов це сам, через тиждень.
# Правило: перевірка встановлення мусить питати «чи ця фіча ЖИВА», а не «чи файли
# на місці». Файли на місці — це не установка.
HOOK_MARKERS = {
    "claude": (Path.home() / ".claude" / "settings.json",
               ("pre_compact.sh", "session_start.sh", "semantic_recall.py")),
    "codex": (Path.home() / ".codex" / "hooks.json", ("codex_lifecycle.py",)),
}


def hooks_wired(agents: list[str] | None) -> dict:
    """Чи згадується хук кита у конфізі агента. None = не знаємо (нема конфіга)."""
    result: dict[str, bool | None] = {}
    for agent in (agents or ["claude", "codex"]):
        marker = HOOK_MARKERS.get(agent)
        if not marker:
            continue
        path, needles = marker
        try:
            text = path.read_text(encoding="utf-8")
        except OSError:
            result[agent] = None
            continue
        result[agent] = any(needle in text for needle in needles)
    return result


def companion_hint() -> dict | None:
    """Одна доречна пропозиція супутника — або нічого. Ніколи не валить doctor."""
    script = KIT / "scripts" / "companions.py"
    if not script.exists():
        return None
    try:
        proc = subprocess.run([sys.executable, str(script), "--json"],
                              capture_output=True, text=True, timeout=15)
        return json.loads(proc.stdout) or None
    except Exception:
        return None


def install_dirs(root: Path) -> None:
    dirs = [
        "memory", "inbox/processed", "tasks/active", "tasks/archive",
        "external/raw", "external/source_cards", "external/distilled",
        "knowledge", "archives/chatgpt", "archives/gemini", "archives/claude",
        "archives/claude-code", "archives/codex", ".index", ".backups", ".sbkit",
    ]
    for rel in dirs:
        (root / rel).mkdir(parents=True, exist_ok=True)
    task_index = root / "tasks" / "_TASKS.md"
    if not task_index.exists():
        task_index.write_text(
            "# Tasks\n\n<!-- registry:start -->\n\n<!-- registry:end -->\n",
            encoding="utf-8",
        )


def detect_prior(root: Path) -> dict:
    """Що вже лежить у цьому корені. Ставити «поверх» безпечно тільки якщо
    ми чесно розуміємо, ЩО саме там лежить."""
    state = load_state(root)
    if state:
        return {"kind": "sbkit", "tier": state.get("tier", "v2"), "state": state}
    if not root.exists() or not any(root.iterdir()):
        return {"kind": "empty", "tier": None, "state": {}}
    # Вольт від безкоштовної версії: тека памʼяті/задач є, керуючого стану нема.
    markers = [root / "memory", root / "tasks", root / "inbox", root / "MEMORY.md"]
    if any(m.exists() for m in markers):
        return {"kind": "v1-vault", "tier": "v1", "state": {}}
    return {"kind": "foreign", "tier": None, "state": {}}


def cmd_install(args: argparse.Namespace) -> int:
    manifest = load_tiers()
    root = as_path(args.root)
    target = args.tier or manifest.get("default", "v2")
    tier_order(target, manifest)                      # валідація імені тиру
    prior = detect_prior(root)

    # 🔴 Пониження тиру нічого не «видаляє» — файли Кита лежать у чекауті, а не
    # у вольті. Але інструкція агента звузиться, і людина цього не очікує.
    if prior["tier"] and tier_order(target, manifest) < tier_order(prior["tier"], manifest) \
            and not args.allow_downgrade:
        raise SystemExit(
            f"ERROR: у {root} вже стоїть {prior['tier']}, а ти ставиш {target}.\n"
            "Дані не постраждають, але інструкція агента звузиться. "
            "Якщо це навмисно — додай --allow-downgrade."
        )

    config = as_path(args.config) if args.config else root / ".sbkit" / "config.toml"
    agents = ["claude", "codex"] if args.agent == "both" else [args.agent]
    previous = prior["state"]
    same = (previous.get("kit_version") == VERSION
            and previous.get("profile") == args.profile
            and previous.get("tier") == target)

    # Бекап перед будь-якою зміною — крім випадку, коли міняти нема чого.
    backup = None
    if not same and root.exists() and any(root.iterdir()):
        backup = create_backup(root)

    install_dirs(root)
    changed = False
    if not config.exists():
        changed |= write_if_changed(config, render_config(root, args.profile, target))
    if "claude" in agents:
        changed |= write_if_changed(
            root / "CLAUDE.md", adapter_text("CLAUDE.md.template", root, config, target))
    if "codex" in agents:
        try:
            changed |= write_if_changed(
                root / "AGENTS.md",
                adapter_text("AGENTS.md.template", root, config, target))
        except FileNotFoundError as exc:
            print(f"ℹ️ AGENTS.md не створено: {exc}")
    merged = sorted(set(previous.get("agents", [])) | set(agents))
    if merged != previous.get("agents", []):
        changed = True

    if same and not changed:
        print(json.dumps({"status": "already-installed", "tier": target,
                          "state": previous}, ensure_ascii=False, indent=2))
        return 0

    state = record_state(root, profile=args.profile, agents=merged,
                         config=config, backup=backup, tier=target)
    status = {"empty": "installed", "v1-vault": "adopted",
              "sbkit": "updated", "foreign": "installed"}[prior["kind"]]
    gained = ([] if prior["tier"] is None
              else [t for t in tiers_upto(target, manifest)
                    if tier_order(t, manifest) > tier_order(prior["tier"], manifest)])
    print(json.dumps({
        "status": status,
        "found_before": prior["kind"],
        "tier": target,
        "layers": tiers_upto(target, manifest),
        "layers_added_now": gained or tiers_upto(target, manifest),
        "files_active": len(resolve_files(target, manifest)),
        "backup": str(backup) if backup else None,
        "state": state,
    }, ensure_ascii=False, indent=2))
    return 0


def cmd_tiers(args: argparse.Namespace) -> int:
    manifest = load_tiers()
    table = tier_table(manifest)
    if args.verify:
        claimed: dict[Path, list[str]] = {}
        for tier in table:
            for rel in tier_files(tier, manifest):
                claimed.setdefault(rel, []).append(tier)
        infra: set[Path] = set()
        for section in ("infrastructure", "source_only"):
            for pattern in manifest.get(section, {}).get("paths", []):
                infra.update(q.relative_to(KIT) for q in KIT.glob(pattern) if q.is_file())
        tracked = subprocess.run(["git", "-C", str(KIT), "ls-files"],
                                 capture_output=True, text=True, check=False)
        problems = []
        for rel, tiers in sorted(claimed.items()):
            if len(tiers) > 1:
                problems.append(f"у кількох тирах ({', '.join(tiers)}): {rel}")
        if tracked.returncode == 0:
            for line in tracked.stdout.splitlines():
                rel = Path(line)
                if rel not in claimed and rel not in infra:
                    problems.append(f"не належить жодному тиру: {rel}")
        for problem in problems:
            print(f"🔴 {problem}")
        print(f"{'🔴' if problems else '✅'} файлів у тирах: {len(claimed)}, "
              f"інфраструктура: {len(infra)}, проблем: {len(problems)}")
        return 1 if problems else 0

    if args.available:
        print("/".join(available_tiers(manifest)))
        return 0
    if args.show_default:
        print(manifest.get("default") or available_tiers(manifest)[-1])
        return 0

    state = load_state(as_path(args.root)) if args.root else {}
    current = state.get("tier")
    for tier in sorted(table, key=lambda t: table[t]["order"]):
        meta = table[tier]
        mark = "▶" if tier == current else " "
        if not tier_available(tier, manifest):
            print(f"  {tier}  {meta['title']}  [не входить у цю збірку]")
            print(f"    {meta['promise']}")
            if meta.get("buy_url"):
                print(f"    → {meta['buy_url']}")
            continue
        access = "публічна" if meta.get("public") else "платна"
        print(f"{mark} {tier}  {meta['title']}  [{access}, файлів {len(tier_files(tier, manifest))}]")
        print(f"    {meta['promise']}")
    if current:
        print(f"\nЗараз у {as_path(args.root)}: {current} "
              f"(шари: {', '.join(tiers_upto(current, manifest))})")
    return 0


def cmd_demo(args: argparse.Namespace) -> int:
    owned_tmp = tempfile.TemporaryDirectory(prefix="sbkit-demo-") if not args.root else None
    root = as_path(args.root) if args.root else Path(owned_tmp.name)
    config = root / "config.toml"
    root.mkdir(parents=True, exist_ok=True)
    config.write_text(render_config(root, "guided"), encoding="utf-8")
    old_config = os.environ.get("SB_CONFIG")
    old_db = os.environ.get("LIBRARIAN_DB_PATH")
    os.environ["SB_CONFIG"] = str(config)
    os.environ["LIBRARIAN_DB_PATH"] = str(root / "demo.db")
    sys.path.insert(0, str(KIT / "scripts"))
    try:
        spec = importlib.util.spec_from_file_location("sbkit_demo_librarian", KIT / "scripts" / "librarian.py")
        if not spec or not spec.loader:
            raise RuntimeError("cannot load librarian")
        lib = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(lib)
        conn = lib.connect()
        samples = [
            ("memory", "/demo/canon.md", "У роботі з клієнтом використовуємо затверджений moodboard і дату рішення."),
            ("external", "/demo/article.md", "Зовнішня стаття радить зберігати всі референси без перевірки."),
            ("tasks", "/demo/task.md", "Підготувати moodboard для клієнта до п'ятниці."),
        ]
        import sqlite_vec
        for source, ref, text in samples:
            conn.execute(
                "INSERT INTO files(ref,source,sha,n_chunks,indexed_at,status) VALUES(?,?,?,?,?,?)",
                (ref, source, "demo", 1, 0, "active"),
            )
            rid = conn.execute(
                "INSERT INTO chunks(source,ref,chunk_idx,text) VALUES(?,?,0,?)",
                (source, ref, text),
            ).lastrowid
            conn.execute(
                "INSERT INTO vchunks(rowid,embedding) VALUES(?,?)",
                (rid, sqlite_vec.serialize_float32([0.0] * 1024)),
            )
        conn.commit()
        result = lib.search_index(
            conn, query="moodboard клієнта", qv=None, source=None, k=3,
            retrieval="keyword", max_per_file=2, after=None, before=None,
            include_undated=False, include_superseded=False, prefer_recent=False,
        )
        conn.close()
        print(json.dumps({"status": "ok", "root": str(root), "demo": result},
                         ensure_ascii=False, indent=2))
    finally:
        if old_config is None:
            os.environ.pop("SB_CONFIG", None)
        else:
            os.environ["SB_CONFIG"] = old_config
        if old_db is None:
            os.environ.pop("LIBRARIAN_DB_PATH", None)
        else:
            os.environ["LIBRARIAN_DB_PATH"] = old_db
        if owned_tmp:
            owned_tmp.cleanup()
    return 0


def migrate_text(text: str, root: Path, profile: str, tier: str = "v2") -> str:
    if re.search(r"(?m)^\[kit\]\s*$", text):
        text = re.sub(r'(?m)^version\s*=\s*".*?"$', f'version = "{VERSION}"', text, count=1)
        text = re.sub(r"(?m)^config_schema\s*=\s*\d+$",
                      f"config_schema = {CONFIG_SCHEMA}", text, count=1)
        if re.search(r"(?m)^tier\s*=", text):
            text = re.sub(r'(?m)^tier\s*=\s*".*?"$', f'tier = "{tier}"', text, count=1)
        else:
            text = re.sub(r"(?m)^(\[kit\]\s*)$", rf'\1\ntier = "{tier}"', text, count=1)
        return text
    header = (
        f"[kit]\nversion = \"{VERSION}\"\nconfig_schema = {CONFIG_SCHEMA}\n"
        f"data_schema = {DATA_SCHEMA}\nprofile = \"{profile}\"\ntier = \"{tier}\"\n\n"
    )
    text = header + text
    if not re.search(r"(?m)^external\s*=", text):
        text = re.sub(
            r'(?m)^(tasks\s*=\s*".*?"\s*)$',
            rf'\1\nexternal = "{root / "external"}"',
            text, count=1,
        )
    return text


def cmd_migrate(args: argparse.Namespace) -> int:
    if args.from_version != "v1":
        raise SystemExit("ERROR: only --from v1 is supported")
    source = as_path(args.source_config)
    root = as_path(args.root)
    target = as_path(args.config) if args.config else root / ".sbkit" / "config.toml"
    text = source.read_text(encoding="utf-8")
    changed = migrate_text(text, root, args.profile, args.tier)
    plan = {
        "from": str(source), "to": str(target), "root": str(root),
        "changes": ["add kit schema/version", "add external layer", "preserve existing paths"],
        "apply": args.apply,
    }
    if not args.apply:
        print(json.dumps(plan, ensure_ascii=False, indent=2))
        return 0
    backup = create_backup(root) if root.exists() and any(root.iterdir()) else None
    install_dirs(root)
    write_if_changed(target, changed)
    agents = ["claude", "codex"]
    write_if_changed(root / "CLAUDE.md",
                     adapter_text("CLAUDE.md.template", root, target, args.tier))
    write_if_changed(root / "AGENTS.md",
                     adapter_text("AGENTS.md.template", root, target, args.tier))
    record_state(root, profile=args.profile, agents=agents, config=target,
                 backup=backup, tier=args.tier)
    plan["backup"] = str(backup) if backup else None
    print(json.dumps(plan, ensure_ascii=False, indent=2))
    return 0


def cmd_backup(args: argparse.Namespace) -> int:
    root = as_path(args.root)
    archive = create_backup(root, as_path(args.destination) if args.destination else None)
    state = load_state(root)
    if state:
        state["last_backup"] = str(archive)
        json_write(state_path(root), state)
    print(archive)
    return 0


def cmd_restore(args: argparse.Namespace) -> int:
    root, archive = as_path(args.root), as_path(args.archive)
    before = restore_backup(root, archive, snapshot=not args.no_snapshot)
    state = load_state(root)
    if state:
        state["last_backup"] = str(archive)
        state["last_restore_undo"] = str(before) if before else None
        json_write(state_path(root), state)
    print(json.dumps({"restored": str(archive),
                      "pre_restore_backup": str(before) if before else None}, indent=2))
    return 0


def cmd_rollback(args: argparse.Namespace) -> int:
    root = as_path(args.root)
    state = load_state(root)
    archive = as_path(args.archive) if args.archive else (
        as_path(state["last_backup"]) if state.get("last_backup") else None
    )
    if archive is None:
        raise SystemExit("ERROR: no rollback backup recorded")
    before = restore_backup(root, archive, snapshot=True)
    restored = load_state(root)
    if restored:
        restored["last_backup"] = str(archive)
        restored["last_restore_undo"] = str(before)
        json_write(state_path(root), restored)
    print(json.dumps({"rolled_back_to": str(archive), "undo_backup": str(before)}, indent=2))
    return 0


def cmd_upgrade(args: argparse.Namespace) -> int:
    """Підняти версію Кита і/або тир. Обидва рухи — бекап-перший і ідемпотентні."""
    manifest = load_tiers()
    root = as_path(args.root)
    state = load_state(root)
    if not state:
        prior = detect_prior(root)
        hint = ("Схоже, це вольт безкоштовної версії — став поверх нього: "
                f"`python3 sbkit.py install --tier v2 --root {root}` "
                "(дані не чіпаються, робиться бекап)."
                if prior["kind"] == "v1-vault" else
                "Спершу `install`.")
        raise SystemExit(f"ERROR: у {root} нема стану Кита. {hint}")

    current = state.get("tier", "v2")
    target = args.to or current
    tier_order(target, manifest)
    if tier_order(target, manifest) < tier_order(current, manifest):
        raise SystemExit(
            f"ERROR: {current} → {target} — це пониження. "
            "Для нього є `install --tier ... --allow-downgrade`."
        )
    if state.get("kit_version") == VERSION and target == current:
        print(json.dumps({"status": "up-to-date", "version": VERSION, "tier": current},
                         ensure_ascii=False))
        return 0

    backup = create_backup(root)
    config = as_path(state["config"])
    profile = state.get("profile", "guided")
    write_if_changed(config,
                     migrate_text(config.read_text(encoding="utf-8"), root, profile, target))
    agents = state.get("agents", ["claude", "codex"])
    if "claude" in agents:
        write_if_changed(root / "CLAUDE.md",
                         adapter_text("CLAUDE.md.template", root, config, target))
    if "codex" in agents:
        write_if_changed(root / "AGENTS.md",
                         adapter_text("AGENTS.md.template", root, config, target))
    record_state(root, profile=profile, agents=agents, config=config,
                 backup=backup, tier=target)
    print(json.dumps({
        "status": "upgraded", "version": VERSION,
        "tier_from": current, "tier_to": target,
        "layers": tiers_upto(target, manifest),
        "files_active": len(resolve_files(target, manifest)),
        "backup": str(backup),
    }, ensure_ascii=False, indent=2))
    return 0


def cmd_update(args: argparse.Namespace) -> int:
    """Одна команда для того, у кого Кит УЖЕ стоїть: принести фікси, підняти стан,
    скласти СПИСОК ДІЙ і не дати про нього забути.

    Порядок обовʼязковий і саме такий: `upgrade` без `pull` відрапортує «up-to-date»
    і збреше — нові файли приносить лише git. Далі — головне: те, що приїхало,
    перетворюється на задачі, які висять у хуках, поки не будуть ЗРОБЛЕНІ
    (див. scripts/update_actions.py).
    """
    sys.path.insert(0, str(KIT / "scripts"))
    try:
        import update_actions as UA
    except ModuleNotFoundError:
        # Безкоштовний тир везе цей файл, але не везе примус застосування — і це
        # чесно: там оновлення підтягуються звичайним git pull, без черги задач.
        # Речення замість стектрейсу: людина має зрозуміти, що вона зробила не так.
        print(
            "ℹ️ Черга оновлень входить у платний тир.\n"
            "   Тут оновлення підтягуються так:  git pull --ff-only\n"
            "   Що змінилось — у CHANGELOG.md."
        )
        return 0

    if args.ack:
        print("✅ знято" if UA.ack(args.ack) else f"нема такої дії: {args.ack}")
        return 0
    if args.status:
        text = UA.notice()
        print(text or "✅ незастосованих оновлень немає")
        return 1 if text else 0

    def git(*a: str) -> subprocess.CompletedProcess:
        return subprocess.run(["git", "-C", str(KIT), *a], capture_output=True, text=True)

    if not (KIT / ".git").exists():
        raise SystemExit(
            "ERROR: твоя копія Кита — не git-репозиторій, оновлення приносити нічим.\n"
            "       Напиши автору: копію треба перевидати як репо, і далі оновлення "
            "стають однією командою."
        )
    dirty = git("status", "--porcelain").stdout.strip()
    if dirty:
        raise SystemExit(
            "ERROR: у теці Кита є власні зміни — оновлення зупинено, щоб їх не затерти.\n"
            f"{dirty[:400]}\n"
            "       🔴 Тека Кита має лишатись недоторканою: твої дані живуть у вольті, "
            "не тут.\n"
            "       Прибрати свої правки: git -C <кит> stash   (або git restore .)"
        )

    before = git("rev-parse", "HEAD").stdout.strip()
    pull = git("pull", "--ff-only")
    if pull.returncode != 0:
        raise SystemExit("ERROR: git pull не пройшов.\n" + (pull.stderr or pull.stdout).strip())
    after = git("rev-parse", "HEAD").stdout.strip()

    if before == after:
        print("✅ нових оновлень немає (копія вже на останньому стані)")
        left = UA.notice()
        if left:
            print("\n" + left)
            return 1
        return 0

    changed = [f for f in git("diff", "--name-only", before, after).stdout.split("\n") if f]
    commits = [c for c in git("log", "--oneline", f"{before}..{after}").stdout.split("\n") if c]

    root = as_path(args.root)
    upgraded = "пропущено"
    try:
        cmd_upgrade(argparse.Namespace(root=str(root), to=None))
        upgraded = "ok"
    except SystemExit as exc:  # стану немає — це не привід валити оновлення
        upgraded = str(exc)

    whats_new = root / ".sbkit" / "WHATS-NEW.md"
    whats_new.parent.mkdir(parents=True, exist_ok=True)
    data = UA.plan(changed, commits=commits, kit=KIT, whats_new=whats_new)
    whats_new.write_text(
        f"# Що приїхало {dt.datetime.now().strftime('%d.%m.%Y %H:%M')}\n\n"
        f"Кит: `{KIT}` · {before[:7]} → {after[:7]} · файлів змінено: {len(changed)}\n\n"
        "## Зміни\n" + "".join(f"- {c}\n" for c in commits) +
        "\n## Що треба зробити (це не список для читання — це задачі)\n" +
        "".join(f"- **[{a['id']}]** {a['why']}\n      `{a['command']}`\n"
                for a in data["actions"]) +
        "\n> Дії класу «замір» знімуться самі, коли стануть правдою. "
        "Дії класу «підтвердження» — лише `sbkit.py update --ack <id>`.\n",
        encoding="utf-8")

    print(f"⬇️  принесено: {len(commits)} змін, {len(changed)} файлів  ({before[:7]} → {after[:7]})")
    print(f"⬆️  стан Кита: {upgraded}")
    print(f"📄 що саме приїхало: {whats_new}")
    print()
    print(UA.notice() or "✅ дій не потрібно — оновлення суто текстове")
    return 1 if data["actions"] else 0


def cmd_health(args: argparse.Namespace) -> int:
    command = [sys.executable, str(KIT / "scripts" / "library_health.py"),
               "--root", str(as_path(args.root)), "--format", args.format]
    return subprocess.run(command, check=False).returncode


def parser() -> argparse.ArgumentParser:
    ap = argparse.ArgumentParser(description=f"SecondBrainKit {VERSION}")
    sub = ap.add_subparsers(dest="command", required=True)
    p = sub.add_parser("doctor")
    p.add_argument("--config")
    p.add_argument("--root", default=DEFAULT_ROOT)
    p.set_defaults(func=cmd_doctor)
    p = sub.add_parser("demo")
    p.add_argument("--root")
    p.set_defaults(func=cmd_demo)
    p = sub.add_parser("install", help="поставити або підхопити наявне; безпечно поверх усього")
    p.add_argument("--root", default=DEFAULT_ROOT)
    p.add_argument("--config")
    p.add_argument("--tier", help="v1 / v2 / v3 (за замовчуванням — з TIERS.toml)")
    p.add_argument("--allow-downgrade", action="store_true")
    p.add_argument("--profile", choices=("guided", "advanced"), default="guided")
    p.add_argument("--agent", choices=("claude", "codex", "both"), default="both")
    p.set_defaults(func=cmd_install)
    p = sub.add_parser("tiers", help="які тири є, що стоїть зараз")
    p.add_argument("--root", default=DEFAULT_ROOT)
    p.add_argument("--verify", action="store_true",
                   help="перевірити, що кожен файл репо належить рівно одному тиру")
    p.add_argument("--available", action="store_true",
                   help="тільки список тирів, які є в цій збірці (для install.sh)")
    p.add_argument("--default", dest="show_default", action="store_true",
                   help="тир за замовчуванням для цієї збірки")
    p.set_defaults(func=cmd_tiers)
    p = sub.add_parser("migrate")
    p.add_argument("--from", dest="from_version", required=True, choices=("v1",))
    p.add_argument("--source-config", required=True)
    p.add_argument("--tier", default="v2")
    p.add_argument("--root", default=DEFAULT_ROOT)
    p.add_argument("--config")
    p.add_argument("--profile", choices=("guided", "advanced"), default="guided")
    p.add_argument("--apply", action="store_true")
    p.set_defaults(func=cmd_migrate)
    p = sub.add_parser("upgrade", help="підняти версію і/або тир")
    p.add_argument("--root", default=DEFAULT_ROOT)
    p.add_argument("--to", help="цільовий тир, напр. v3")
    p.set_defaults(func=cmd_upgrade)
    p = sub.add_parser("backup")
    p.add_argument("--root", default=DEFAULT_ROOT)
    p.add_argument("--destination")
    p.set_defaults(func=cmd_backup)
    p = sub.add_parser("restore")
    p.add_argument("--root", default=DEFAULT_ROOT)
    p.add_argument("--archive", required=True)
    p.add_argument("--no-snapshot", action="store_true")
    p.set_defaults(func=cmd_restore)
    p = sub.add_parser("rollback")
    p.add_argument("--root", default=DEFAULT_ROOT)
    p.add_argument("--archive")
    p.set_defaults(func=cmd_rollback)
    p = sub.add_parser("update", help="принести оновлення і застосувати їх (pull → upgrade → список дій)")
    p.add_argument("--root", default=DEFAULT_ROOT)
    p.add_argument("--status", action="store_true", help="що лишилось незастосованим")
    p.add_argument("--ack", metavar="ID", help="підтвердити дію, яку не можна заміряти")
    p.set_defaults(func=cmd_update)

    p = sub.add_parser("health")
    p.add_argument("--root", default=DEFAULT_ROOT)
    p.add_argument("--format", choices=("text", "json"), default="text")
    p.set_defaults(func=cmd_health)
    return ap


def main() -> int:
    args = parser().parse_args()
    return int(args.func(args) or 0)


if __name__ == "__main__":
    raise SystemExit(main())
